In [8]:
import numpy as np

### Задание 1
Создайте numpy array с элементами 
от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [9]:
N = -5
np.arange(N,0,0.99)

array([-5.  , -4.01, -3.02, -2.03, -1.04, -0.05])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [10]:
np.diag(np.arange(N,0,1))

array([[-5,  0,  0,  0,  0],
       [ 0, -4,  0,  0,  0],
       [ 0,  0, -3,  0,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  0,  0,  0, -1]])

In [16]:
sum(sum(list(np.diag(np.arange(N,0,1)))))

-15

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [23]:
a = np.array( [ [4, 2, 1], [1, 3,0],[0,5,4] ] )
b = np.array( [4, 12,-3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [25]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [30]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [52]:
def cosine( users_stats, next_user_stats ):
    c = 0
    for index,i in enumerate(users_stats):
        aLength = np.linalg.norm( i )
        bLength = np.linalg.norm( next_user_stats )
        if np.dot( i, next_user_stats ) / ( aLength * bLength ) > c:
            c = np.dot( i, next_user_stats ) / ( aLength * bLength )
            d = index 
    print('Самый похожий пользователь с индексом - ', d)

In [53]:
cosine( users_stats, next_user_stats )

Самый похожий пользователь с индексом -  7
